### USER ROUTES

# List all users
GET http://localhost:3001/api/users

###

### AUTH ROUTES

# Login
POST http://localhost:3001/api/sessions
Content-Type: application/json

{
  "username": "alice123",
  "password": "ciao"
}

###
# Get current session
GET http://localhost:3001/api/sessions/current

###
# Logout
DELETE http://localhost:3001/api/sessions/current

###

### CARD ROUTES

# List all cards
GET http://localhost:3001/api/cards

###
# Get card by id
GET http://localhost:3001/api/cards/1

### GAME ROUTES



###
# create a new game
GET http://localhost:3001/api/start-game

###
# Update a game
PATCH http://localhost:3001/api/games/1
Content-Type: application/json

{
  "gameId": 1,
  "totalCards": 8,
  "outcome": "win"
}

###
# Delete a game
DELETE http://localhost:3001/api/games/1

###
# Get match history (requires authentication)
GET http://localhost:3001/api/games/alfio123

### ROUND ROUTES

# Create a new round
POST http://localhost:3001/api/rounds/
Content-Type: application/json
Cookie: connect.sid=s%3AzCHy3yloqIJWIyJsUFmQ23b_hOZiCm91.De1alg%2BxIqHj0dTINz%2B%2BgP1XUuKgCLTenT77SdgLiQw;

{
  "gameId": 2,
  "cardId": 3,
  "won": 1,
  "roundNumber": 6
}

###
# Get rounds by game (requires authentication)
GET http://localhost:3001/api/rounds/608

###
# Update a round
PATCH http://localhost:3001/api/rounds/1
Content-Type: application/json

{
  "misfortuneLeft": 2,
  "misfortuneRight": 8,
  "cardId": 1,
  "timeStamp": "2025-06-19T12:01:00.000Z"
}
